name: Dev CI/CD Infra (SAM)

on:
  push:
    branches:
      - develop

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ secrets.CICD_GOVER }}
      - name: Test get-function Lambda
        run: cd aws-sam/get-function && go test -v ./ && cd ../../
      - name: Test put-function Lambda
        run: cd aws-sam/get-function && go test -v ./ && cd ../../
  
  build-deploy-infra:
    needs: test-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build
        working-directory: aws-sam
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: aws-sam

  test-and-build-site:
    needs: build-deploy-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: cd aws-sam/resume-site && npm install && cd ../../
      # - name: Run test
      #   run: cd aws-sam/resume-site && npm test && cd ../../
      - name: Build
        run: npm run build

  deploy-s3:
    needs: test-and-build-site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: aws-sam/resume-site


