name: Build, Test, and Deploy

on: 
  push:
    # Condition for which branch to check
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: 17.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm run-script test

  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout source code
  #     uses: actions/checkout@v3

  #   - name: Generate deployment package
  #     run: zip -r deploy.zip . -x '*.git*'

  #   - name: Deploy to Elastic Beanstalk
  #     uses: einaregilsson/beanstalk-deploy@v20
  #     with: 

  #       aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  #       application_name: cloud-resume
  #       environment_name: cloud-resume-env

  #       region: "us-east-1"
  #       deployment_package: deploy.zip
  #       version_label: "v1"
  #       use_existing_version_if_available: true