name: Build, Test, and Deploy

on: 
  push:
    # Condition for which branch to check
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: 17.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present

    # - name: Test
    #   run: npm run test:ci

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    env: 
      BUCKET: artaly-cloud
      DIST: build
      REGION: us-east-1
      DIST_ID: E395F887NV3PKK

    timeout-minutes: 10

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}

    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: 17.x

    - name: Install dependencies
      run: npm install

    - name: Build static website
      run: npm run build --if-present

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"