name: Status Checker

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review', 'review_requested']
    branches:
      - develop
      - main

jobs:
  status-check:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: cd aws-sam/resume-site && npm install && cd ../../
      - name: Run unit tests
        run: cd aws-sam/resume-site && npm test && cd ../../ 
