name: Test Lambda Functions

on:
  push:
    branches:
      - develop

jobs:
  test-lambda:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.6'
      - name: Test get-function Lambda
        run: cd aws-sam/get-function && go test -v ./ && cd ../../
      - name: Test put-function Lambda
        run: cd aws-sam/get-function && go test -v ./ && cd ../../
